- client/components/ShoppingCart.js
- package-lock.json
- server/api/index.js
> Fix api index

- client/components/allProducts.js
- client/components/index.js
- client/index.js
- client/routes.js
- client/store/index.js
- client/store/products.js
- package-lock.json
- package.json
- server/api/index.js
- server/api/products.js
> All products

- client/components/ShoppingCart.js
- client/components/allProducts.js
- client/components/index.js
- client/components/main.js
- client/routes.js
> added welcome

- server/api/products.js
> back-end modified to include categories for reviews

- server/db/models/product.js
> default image on product is /gray.png

- client/components/SingleProduct.js
- client/components/reviewForm.js
- client/routes.js
- client/store/index.js
- client/store/reviews.js
- server/api/reviews.js
> feature(reviews) display reviews on single product

- client/components/allProducts.js
- public/index.html
- public/style.css
> style(css) added flex to allproducts view

- client/components/ShoppingCart.js
- client/components/SingleProduct.js
- client/routes.js
- client/store/index.js
- client/store/order_products.js
- client/store/orders.js
- client/store/products.js
- package-lock.json
- server/api/index.js
- server/api/order_products.js
> Shopping cart with seed

- client/components/SingleProduct.js
- client/routes.js
- client/store/index.js
- client/store/products.js
- server/api/index.js
> fix(conflicts) merge conflicts on product

- client/components/allProducts.js
- server/api/products.js
> Reviewform

- client/store/products.spec.js
- routes.test.js
- server/db/models/product.spec.js
> tests: complete products redux tests and fix product route tests

- client/components/SingleProduct.js
> feat(button) add to cart button on single prod

- client/components/SingleProduct.js
> fix(single product) change state reference

- client/components/ShoppingCart.js
> fix(cart) display cart fixed state.products.allProducts

- client/components/allProducts.js
> fix(filters on products the searches now refine each other)

- client/components/main.js
> feat(home link) site title links to /home

- client/components/main.js
> Nav Link goes to home and refreshes search

- client/components/ShoppingCart.js
- client/components/SingleProduct.js
- client/components/allProducts.js
- client/routes.js
- client/store/order_products.js
- client/store/user.js
- package-lock.json
- package.json
- server/api/index.js
- server/api/order_products.js
- server/api/orders.js
- server/db/models/order_product.js
> Add to cart function

- client/components/SingleProduct.js
- client/components/allProducts.js
- server/api/orders.js
- server/db/models/order_product.js
> fix(addtocart functionality)

- client/components/main.js
- public/style.css
> basic nav styling

- client/components/main.js
- public/style.css
> add tagline

- server/api/orders.js
- server/auth/index.js
> More cart functions

- client/components/SingleProduct.js
> fix(possibly completely fixed addToCart somtimes shows Qty of 0)

- seed.js
> change product-categories on seed

- public/style.css
> remove flex-grow

- client/components/SingleProduct.js
> fix(reviews) form shows only if logged in

- client/components/ShoppingCart.js
- client/components/SingleProduct.js
- client/store/order_products.js
- client/store/orders.js
> feature(added alerts and disable button)

- client/components/ConfirmationPage.js
- client/components/ShippingOrderForm.js
- client/components/index.js
- client/routes.js
- package-lock.json
> feat(order-confirmation):successfully renders after "submit order"

- client/components/allProducts.js
- client/routes.js
> Hot reload2

- server/api/orders.js
> fix(error) no more 404 for /api/orders when logged out

- client/components/SingleProduct.js
- client/components/allProducts.js
- client/components/main.js
- package-lock.json
> feature(removed buttons for unlogged users)

- client/components/ShoppingCart.js
- client/components/SingleProduct.js
- client/components/allProducts.js
- client/routes.js
- client/store/cart.js
- client/store/index.js
- client/store/order_products.js
- server/api/orders.js
> fix(reload) reload works for adding to cart

- client/components/SingleProduct.js
> fix add to cart from single

- client/components/allProducts.js
- client/components/main.js
- public/index.html
- public/style.css
> Start styling
